# Generated by Django 4.2 on 2024-10-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milkCalculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MilkView',
        ),
    ]
