# Generated by Django 4.2 on 2024-10-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkCalculator', '0002_delete_milkview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkdata',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='milkdata',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
