# Generated by Django 4.2 on 2024-10-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkCalculator', '0003_alter_milkdata_price_alter_milkdata_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkdata',
            name='total_qty',
            field=models.FloatField(),
        ),
    ]
