# Generated by Django 4.2 on 2024-10-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilkView',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'milk_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MilkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('qty', models.FloatField()),
                ('total_qty', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
